server:
  port: 8080
  
spring:
  application:
    name: SpringSecurityOAuth2.xApp
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: <your client id>
            client-secret: <your client secret>
            scope:
             - email
             - public_profile
