server:
  port: 8080
  
spring:
  application:
    name: SpringSecurityOAuth2.xApp
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1797346420709247
            client-secret: c6b9427b226e3ac0af3acfbafffb20cc
            scope:
             - email
             - public_profile
